-file("d:/Elixir/Erlang OTP/lib/parsetools-2.4/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(scanner).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("src/scanner.xrl", 43).

analyze(TokenChars) ->

    IsKW = lists:member(TokenChars, ["abstract","arguments","await","boolean","break" ,"byte" ,"case" ,"catch","char" ,"class","const","continue","debugger","default","delete" ,"do","double" ,"else" 	,"enum" ,"eval","export" ,"extends" ,"false" ,"final","finally" ,"float" ,"for","function","goto","if","implements" ,"import","in" ,"instanceof" ,"int" ,"interface","let" ,"long","native","new","null","package" ,"private" ,"protected","public" ,"return","short" ,"static","super" ,"switch" ,"synchronized","this","throw" ,"throws" ,"transient" ,"true","try" ,"typeof","var","void","volatile","while","with","yield","Array","Date","eval","function","hasOwnProperty","Infinity","isFinite","isNaN","isPrototypeOf","length","Math","NaN","Number","Object","prototype","String","toString","undefined","valueOf","forEach","getClass","java","JavaArray","javaClass","JavaObject","JavaPackage","alert","all","anchor","anchors","area","assign","blur","button","checkbox","clearInterval","clearTimeout","clientInformation","close","closed","confirm","constructor","crypto","decodeURI","decodeURIComponent","defaultStatus","element","elements","embed","embeds","encodeURI","encodeURIComponent","escape","event","fileUpload","focus","form","forms","frame","innerHeight","innerWidth","layer","layers","link","location","mimeTypes","navigate","navigator","frames","frameRate","hidden","history","image","images","offscreenBuffering","open","opener","option","outerHeight","outerWidth","packages","pageXOffset","pageYOffset","parent","parseFloat","parseInt","pkcs11","plugin","prompt","propertyIsEnum","reset","screenX","screenY","scroll","secure","select","self","setInterval","setTimeout","status","submit","taint","textarea","top","unescape","untaint","window","onblur","onclick","onerror","onfocus","onkeydown","onkeypress","onkeyup","onmouseover","onload","onmouseup","onmousedown","onsubmit"]),
    if
        IsKW -> {keyword, TokenChars};
        true -> {identifier, TokenChars}
    end.

%Punctuators
% \{|\(|\)|\[|\]|\.|\.\.\.|\;|\,|\<|\>|\<\=|\>\=|\=\=|\!\=|\=\=\=|\!\=\=|\+|\-|\*|\%|\*\*|\+\+|\-\-|\<\<|\>\>|\>\>\>|\&|\||\^|\!|\~|\&\&|\|\||\?\?|\?|\:|\=|\+\=|\-\=|\*\=|\%\=|\*\*\=|\<\<\=|\>\>\=|\>\>\>\=|\&\=|\|\=|\^\=|\&\&\=|\|\|\=|\?\?\=|\=\>|\/|\/\=|\} 

% Principales Keywords
% "abstract","arguments","await","boolean","break" 	,"byte" 	,"case" 	,"catch","char" ,"class" 	,"const" 	,"continue","debugger","default","delete" ,"do","double" 	,"else" 	,"enum" ,"eval","export" ,"extends" ,"false" 	,"final","finally" ,"float" ,"for","function","goto","if","implements" 	,"import","in" ,"instanceof" ,"int" ,"interface","let" ,"long" 	,"native","new","null","package" ,"private" 	,"protected","public" 	,"return" ,"short" ,"static","super" ,"switch" 	,"synchronized","this","throw" ,"throws" ,"transient" ,"true","try" 	,"typeof" 	,"var"	,"void","volatile","while","with","yield"

% Keywords de Objects, Properties, and Methods
% ,"Array","Date","eval","function","hasOwnProperty","Infinity","isFinite","isNaN","isPrototypeOf","length","Math","NaN","Number","Object","prototype","String","toString","undefined","valueOf","forEach"

% Java Reserved Words
% ,"getClass","java","JavaArray","javaClass","JavaObject","JavaPackage"

% Other Reserved Words
% ,"alert","all","anchor","anchors","area","assign","blur","button","checkbox","clearInterval","clearTimeout","clientInformation","close","closed","confirm","constructor","crypto","decodeURI","decodeURIComponent","defaultStatus","element","elements","embed"","embeds","encodeURI","encodeURIComponent","escape","event","fileUpload","focus","form","forms","frame","innerHeight","innerWidth","layer","layers","link","location","mimeTypes","navigate","navigator","frames","frameRate","hidden","history","image","images","offscreenBuffering","open","opener","option","outerHeight","outerWidth","packages","pageXOffset","pageYOffset","parent","parseFloat","parseInt","pkcs11","plugin","prompt","propertyIsEnum","reset","screenX","screenY","scroll","secure","select","self","setInterval","setTimeout","status","submit","taint","textarea","top","unescape","untaint","window"

% HTML Event Handlers
% ,"onblur","onclick","onerror","onfocus","onkeydown","onkeypress","onkeyup","onmouseover","onload","onmouseup","onmousedown","onsubmit"

% Escape Sequences
% \b\f\n\r\t\e\v\s\d


-file("d:/Elixir/Erlang OTP/lib/parsetools-2.4/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transition state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("src/scanner.erl", 337).
yystate() -> 83.

yystate(90, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(82, Ics, Line, Tlen+1, Action, Alen);
yystate(90, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,90};
yystate(89, [110|Ics], Line, Tlen, _, _) ->
    yystate(81, Ics, Line, Tlen+1, 2, Tlen);
yystate(89, [95|Ics], Line, Tlen, _, _) ->
    yystate(85, Ics, Line, Tlen+1, 2, Tlen);
yystate(89, [48|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 2, Tlen);
yystate(89, [49|Ics], Line, Tlen, _, _) ->
    yystate(89, Ics, Line, Tlen+1, 2, Tlen);
yystate(89, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,89};
yystate(88, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,88};
yystate(87, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(86, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(86, [46|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 10, Tlen);
yystate(86, [45|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, 10, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,86};
yystate(85, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, [110|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(84, [95|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 0, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(84, Ics, Line, Tlen+1, 0, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,84};
yystate(83, [127|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [126|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [125|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [124|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [123|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [96|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [94|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [93|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [92|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [91|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [64|Ics], Line, Tlen, _, _) ->
    yystate(87, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [63|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [62|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [61|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [60|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [59|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [58|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [48|Ics], Line, Tlen, _, _) ->
    yystate(5, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [47|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [46|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [45|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [44|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [43|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [42|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [41|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [40|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [39|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [38|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [37|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [36|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [35|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [34|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [33|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [32|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [27|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [10|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line+1, Tlen+1, 11, Tlen);
yystate(83, [8|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [9|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 7 ->
    yystate(87, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 13 ->
    yystate(79, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 14, C =< 26 ->
    yystate(87, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 28, C =< 31 ->
    yystate(87, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 49, C =< 57 ->
    yystate(44, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(11, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(11, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 128 ->
    yystate(87, Ics, Line, Tlen+1, 11, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,83};
yystate(82, [110|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(90, Ics, Line, Tlen+1, 0, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(82, Ics, Line, Tlen+1, 0, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,82};
yystate(81, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line};
yystate(80, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(80, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(80, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(80, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,80};
yystate(79, [127|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [32|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [27|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [8|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [9|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 13 ->
    yystate(79, Ics, Line, Tlen+1, 6, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,79};
yystate(78, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,78};
yystate(77, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(76, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,76};
yystate(75, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line};
yystate(74, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(84, Ics, Line, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,74};
yystate(73, [61|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, [47|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, [42|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 41 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 60 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, [C|Ics], Line, Tlen, _, _) when C >= 62 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(73, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,73};
yystate(72, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(72, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, Action, Alen);
yystate(72, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,72};
yystate(71, [10|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,71};
yystate(70, [101|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 1, Tlen);
yystate(70, [69|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 1, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,70};
yystate(69, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line};
yystate(68, [110|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(68, [101|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 0, Tlen);
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 0, Tlen);
yystate(68, [69|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 0, Tlen);
yystate(68, [46|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 0, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(68, Ics, Line, Tlen+1, 0, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,68};
yystate(67, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(66, [101|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [69|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,66};
yystate(65, [47|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 12, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(38, Ics, Line, Tlen+1, 12, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line,65};
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,64};
yystate(63, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,63};
yystate(62, [101|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [69|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(62, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,62};
yystate(61, [110|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [95|Ics], Line, Tlen, _, _) ->
    yystate(53, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 55 ->
    yystate(61, Ics, Line, Tlen+1, 3, Tlen);
yystate(61, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,61};
yystate(60, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,60};
yystate(59, [124|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(59, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,59};
yystate(58, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(58, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,58};
yystate(57, [105|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, [104|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, [103|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, [47|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 102 ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 106 ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,57};
yystate(56, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(56, [46|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 10, Tlen);
yystate(56, [43|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(72, Ics, Line, Tlen+1, 10, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,56};
yystate(55, [61|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,55};
yystate(54, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,54};
yystate(53, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(53, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,53};
yystate(52, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(51, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line+1, Tlen+1, Action, Alen);
yystate(51, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(51, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(51, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,51};
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 1, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, 1, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,50};
yystate(49, [47|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 13, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(38, Ics, Line, Tlen+1, 13, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,49};
yystate(48, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(48, [42|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,48};
yystate(47, [96|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [92|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, 17, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,47};
yystate(46, [46|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 10, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(70, Ics, Line, Tlen+1, 10, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,46};
yystate(45, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 55 ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [110|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [101|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [69|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [46|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(44, Ics, Line, Tlen+1, 0, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,44};
yystate(43, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(42, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,42};
yystate(41, [105|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, [104|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, [103|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, [47|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 102 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 106 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,41};
yystate(40, [92|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [39|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [10|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line+1, Tlen+1, 17, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(16, Ics, Line, Tlen+1, 17, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,40};
yystate(39, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(38, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,38};
yystate(37, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line};
yystate(36, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(36, [60|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,36};
yystate(35, [92|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 14, Tlen);
yystate(35, [34|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 14, Tlen);
yystate(35, [10|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line+1, Tlen+1, 14, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(51, Ics, Line, Tlen+1, 14, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(51, Ics, Line, Tlen+1, 14, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(51, Ics, Line, Tlen+1, 14, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(51, Ics, Line, Tlen+1, 14, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line,35};
yystate(34, [95|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 1, Tlen);
yystate(34, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(34, Ics, Line, Tlen+1, 1, Tlen);
yystate(34, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,34};
yystate(33, [47|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(33, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(33, Ics, Line, Tlen+1, 8, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,33};
yystate(32, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line+1, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(32, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,32};
yystate(31, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line+1, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(31, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,31};
yystate(30, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line+1, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(30, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(30, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,30};
yystate(29, [110|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 4, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line, Tlen+1, 4, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(29, Ics, Line, Tlen+1, 4, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(29, Ics, Line, Tlen+1, 4, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(29, Ics, Line, Tlen+1, 4, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,29};
yystate(28, [92|Ics], Line, Tlen, _, _) ->
    yystate(32, Ics, Line, Tlen+1, 15, Tlen);
yystate(28, [39|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 15, Tlen);
yystate(28, [10|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line+1, Tlen+1, 15, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 40, C =< 91 ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(16, Ics, Line, Tlen+1, 15, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line,28};
yystate(27, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line+1, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(27, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(27, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,27};
yystate(26, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(50, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, [105|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [104|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [103|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [47|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [42|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [10|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line+1, Tlen+1, 13, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 41 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 102 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, [C|Ics], Line, Tlen, _, _) when C >= 106 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(25, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,25};
yystate(24, [62|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(24, [61|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,24};
yystate(23, [96|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 16, Tlen);
yystate(23, [92|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 16, Tlen);
yystate(23, [10|Ics], Line, Tlen, _, _) ->
    yystate(15, Ics, Line+1, Tlen+1, 16, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, 16, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, 16, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, 16, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, 16, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line,23};
yystate(22, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line+1, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(22, [C|Ics], Line, Tlen, Action, Alen) when C >= 43 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,22};
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(19, [92|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [34|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [10|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line+1, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(51, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(51, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 91 ->
    yystate(51, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 93 ->
    yystate(51, Ics, Line, Tlen+1, 17, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line,19};
yystate(18, [101|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [95|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [69|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(18, Ics, Line, Tlen+1, 1, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,18};
yystate(17, [47|Ics], Line, Tlen, _, _) ->
    yystate(25, Ics, Line, Tlen+1, 13, Tlen);
yystate(17, [42|Ics], Line, Tlen, _, _) ->
    yystate(9, Ics, Line, Tlen+1, 13, Tlen);
yystate(17, [10|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line+1, Tlen+1, 13, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 41 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 43, C =< 46 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(17, [C|Ics], Line, Tlen, _, _) when C >= 48 ->
    yystate(30, Ics, Line, Tlen+1, 13, Tlen);
yystate(17, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,17};
yystate(16, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(20, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line+1, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,16};
yystate(15, [96|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line+1, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 91 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 93, C =< 95 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Tlen, Action, Alen) when C >= 97 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line};
yystate(13, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(13, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,13};
yystate(12, [62|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(12, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,12};
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [36|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(11, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(11, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(11, Ics, Line, Tlen+1, 5, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,11};
yystate(10, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(10, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,10};
yystate(9, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line+1, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(9, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(9, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,9};
yystate(8, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(8, [38|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,8};
yystate(7, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line};
yystate(6, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(22, Ics, Line+1, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 41 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 43, C =< 46 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(6, [C|Ics], Line, Tlen, Action, Alen) when C >= 48 ->
    yystate(22, Ics, Line, Tlen+1, Action, Alen);
yystate(6, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,6};
yystate(5, [120|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [111|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [110|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [101|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [98|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [88|Ics], Line, Tlen, _, _) ->
    yystate(13, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [79|Ics], Line, Tlen, _, _) ->
    yystate(45, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [69|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [66|Ics], Line, Tlen, _, _) ->
    yystate(77, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [46|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(44, Ics, Line, Tlen+1, 0, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,5};
yystate(4, [62|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 10, Tlen);
yystate(4, [61|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 10, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,4};
yystate(3, [63|Ics], Line, Tlen, _, _) ->
    yystate(63, Ics, Line, Tlen+1, 10, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,3};
yystate(2, [101|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(2, [95|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 1, Tlen);
yystate(2, [69|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 1, Tlen);
yystate(2, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(2, Ics, Line, Tlen+1, 1, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,2};
yystate(1, [105|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [104|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [103|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [47|Ics], Line, Tlen, _, _) ->
    yystate(57, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(38, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 46 ->
    yystate(38, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 102 ->
    yystate(38, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, [C|Ics], Line, Tlen, _, _) when C >= 106 ->
    yystate(38, Ics, Line, Tlen+1, 9, Tlen);
yystate(1, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,1};
yystate(0, [61|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 11, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars);
yyaction(1, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars);
yyaction(2, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars);
yyaction(3, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars);
yyaction(4, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars);
yyaction(5, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars);
yyaction(6, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars);
yyaction(7, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars);
yyaction(8, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars);
yyaction(9, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars);
yyaction(10, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars);
yyaction(11, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars);
yyaction(12, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars);
yyaction(13, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars);
yyaction(14, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars);
yyaction(15, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars);
yyaction(16, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars);
yyaction(17, TokenLen, YYtcs, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars);
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("src/scanner.xrl", 7).
yyaction_0(TokenChars) ->
     { token, { number, TokenChars } } .

-compile({inline,yyaction_1/1}).
-file("src/scanner.xrl", 8).
yyaction_1(TokenChars) ->
     { token, { number, TokenChars } } .

-compile({inline,yyaction_2/1}).
-file("src/scanner.xrl", 9).
yyaction_2(TokenChars) ->
     { token, { number, TokenChars } } .

-compile({inline,yyaction_3/1}).
-file("src/scanner.xrl", 10).
yyaction_3(TokenChars) ->
     { token, { number, TokenChars } } .

-compile({inline,yyaction_4/1}).
-file("src/scanner.xrl", 11).
yyaction_4(TokenChars) ->
     { token, { number, TokenChars } } .

-compile({inline,yyaction_5/1}).
-file("src/scanner.xrl", 15).
yyaction_5(TokenChars) ->
     { token, analyze (TokenChars) } .

-compile({inline,yyaction_6/1}).
-file("src/scanner.xrl", 18).
yyaction_6(TokenChars) ->
     { token, { special, TokenChars } } .

-compile({inline,yyaction_7/1}).
-file("src/scanner.xrl", 19).
yyaction_7(TokenChars) ->
     { token, { breakLine, TokenChars } } .

-compile({inline,yyaction_8/1}).
-file("src/scanner.xrl", 22).
yyaction_8(TokenChars) ->
     { token, { comment, TokenChars } } .

-compile({inline,yyaction_9/1}).
-file("src/scanner.xrl", 23).
yyaction_9(TokenChars) ->
     { token, { comment, TokenChars } } .

-compile({inline,yyaction_10/1}).
-file("src/scanner.xrl", 26).
yyaction_10(TokenChars) ->
     { token, { operadores, TokenChars } } .

-compile({inline,yyaction_11/1}).
-file("src/scanner.xrl", 28).
yyaction_11(TokenChars) ->
     { token, { operadores, TokenChars } } .

-compile({inline,yyaction_12/1}).
-file("src/scanner.xrl", 29).
yyaction_12(TokenChars) ->
     { token, { operadores, TokenChars } } .

-compile({inline,yyaction_13/1}).
-file("src/scanner.xrl", 33).
yyaction_13(TokenChars) ->
     { token, { regex, TokenChars } } .

-compile({inline,yyaction_14/1}).
-file("src/scanner.xrl", 36).
yyaction_14(TokenChars) ->
     { token, { string, TokenChars } } .

-compile({inline,yyaction_15/1}).
-file("src/scanner.xrl", 37).
yyaction_15(TokenChars) ->
     { token, { string, TokenChars } } .

-compile({inline,yyaction_16/1}).
-file("src/scanner.xrl", 38).
yyaction_16(TokenChars) ->
     { token, { string, TokenChars } } .

-compile({inline,yyaction_17/1}).
-file("src/scanner.xrl", 39).
yyaction_17(TokenChars) ->
     { token, { mistake, TokenChars } } .

-file("d:/Elixir/Erlang OTP/lib/parsetools-2.4/include/leexinc.hrl", 313).
